

/**
 * Static class that contains a listage of the code mirror themes (CSS) available in the platform.
 * 
 * @static
 * @class CodemirrorThemes
 */
var CodemirrorThemes =
[
	"3024-night",
	"3024-day",
	"abcdef",
	"ayu-dark",
	"ayu-mirage",
	"darcula",
	"ambiance",
	"gruvbox-dark",
	"idea",
	"lucario",
	"material-darker",
	"material-ocean",
	"material-palenight",
	"moxer",
	"nord",
	"ssms",
	"yonce",
	"base16-light",
	"base16-dark",
	"bespin",
	"blackboard",
	"cobalt",
	"colorforth",
	"dracula",
	"duotone-light",
	"duotone-dark",
	"eclipse",
	"elegant",
	"erlang-dark",
	"hopscotch",
	"icecoder",
	"isotope",
	"lesser-dark",
	"liquibyte",
	"material",
	"mbo",
	"mdn-like",
	"midnight",
	"monokai",
	"neat",
	"neo",
	"night",
	"oceanic-next",
	"paraiso-dark",
	"paraiso-light",
	"pastel-on-dark",
	"panda-syntax",
	"railscasts",
	"rubyblue",
	"seti",
	"shadowfox",
	"solarized",
	"the-matrix",
	"tomorrow-night-bright",
	"tomorrow-night-eighties",
	"ttcn",
	"twilight",
	"vibrant-ink",
	"xq-dark",
	"xq-light",
	"yeti",
	"zenburn"
];
export {CodemirrorThemes};